name: Run Simulink Tests on Push to dev

on:
  push:
    paths:
      - 'dev/**'  # dev 폴더에 변경 발생 시
    branches:
      - main      # 또는 main 브랜치 기준

jobs:
  simulink-test:
    runs-on: self-hosted  # self-hosted runner에서 실행
    name: Run Simulink Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Simulink tests with MATLAB
        run: |
          "C:\Program Files\MATLAB\R2024a\bin\matlab.exe" -batch "run_simulink_tests"
