name: Run test_0705.m when Tests folder changes

on:
  push:
    branches:
      - test_0705
    paths:
      - BatteryManagementSystem/Tests/**  # 이 경로에 변경이 있을 때만 실행됨

jobs:
  run-matlab-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set PowerShell execution policy (Windows only)
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force

      - name: Run MATLAB test_0705.m
        shell: powershell
        run: |
          $workspace = $env:GITHUB_WORKSPACE
          matlab -batch "run(fullfile('$workspace', 'BatteryManagementSystem', 'Tests', 'test_0705.m'))"


      - name: Run Simulink Test (mldatx)
        shell: powershell
        run: |
          mkdir -p artifacts
          matlab -batch "import sltest.testmanager.*; \
                         tf = sltest.testmanager.TestFile('BMS_ClosedLoop_Test.mldatx'); \
                         resultSet = sltest.testmanager.run(tf); \
                         sltest.testmanager.exportResults(resultSet, 'artifacts/BMS_TestResult.mldatx'); \
                         sltest.testmanager.exportResults(resultSet, 'artifacts/BMS_TestResult.xml', 'ExportFormat', 'JUnit'); \
                         sltest.testmanager.clear; \
                         sltest.testmanager.clearResults;"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: BMS-Simulink-Test-Results
          path: artifacts/
