name: Run MATLAB Test for test_0705

on:
  push:
    branches:
      - test_0705

jobs:
  run-matlab-test:
    name: Run test_0705.m
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run MATLAB test_0705.m
        run: |
          matlab -batch "run('test_0705.m')"
