name: Run MATLAB Test for test_0705

on:
  push:
    branches:
      - test_0705

jobs:
  run-matlab-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set PowerShell policy to allow scripts
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force

      - name: Run MATLAB script with full path
        shell: powershell
        run: matlab -batch "run(fullfile(getenv('GITHUB_WORKSPACE'), 'test_0705.m'))"
