name: Run test_0705.m when Tests folder changes

on:
  push:
    branches:
      - test_0705
    paths:
      - BatteryManagementSystem/Tests/**  # 이 경로에 변경이 있을 때만 실행됨

jobs:
  simulink-test:
    name: Run Simulink Test (.mldatx)
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Artifact Directory
        shell: cmd
        run: mkdir artifacts

      - name: Run Simulink Test using MATLAB
        shell: cmd
        run: |
          matlab -batch "import sltest.testmanager.*; resultSet = sltest.testmanager.run('BatteryManagementSystem/Tests/System/BMS_ClosedLoop_Test.mldatx'); sltest.testmanager.exportResults(resultSet, 'artifacts/BMS_TestResult.mldatx'); sltest.testmanager.exportResults(resultSet, 'artifacts/BMS_TestResult.xml', 'ExportFormat', 'JUnit'); sltest.testmanager.clear; sltest.testmanager.clearResults;"

      - name: Upload Test Result as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BMS-Simulink-Test-Results
          path: artifacts/
