name: Run test_0705.m when Tests folder changes

on:
  push:
    branches:
      - test_0705
    paths:
      - BatteryManagementSystem/Tests/**  # 이 경로에 변경이 있을 때만 실행됨

jobs:
  run-matlab-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set PowerShell execution policy (Windows only)
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force

      - name: Run MATLAB test_0705.m
        shell: powershell
        run: |
          $workspace = $env:GITHUB_WORKSPACE
          matlab -batch "run(fullfile('$workspace', 'BatteryManagementSystem', 'Tests', 'test_0705.m'))"

      - name: Run tests
        uses: matlab-actions/run-tests@v2

      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          
